"""Appendix D table emitter (Section II appendices; plan of 2026-08-21).

ADDITIVE script — touches no gate, no existing module, no stored output. Reads only
out/*.csv and emits LaTeX fragments to out/appendix/. Tree convention throughout
(within-subject z, sample std ddof=1); permutation p = 20,000 within-participant
shuffles, fixed seeds, two-sided on |rho|. Film labels appear only as episode
identifiers (episode-only ruling). Run:
    /home/dalton/.pyenv/versions/3.11.9/bin/python3 analysis/appendix_tables.py
"""
import os
import numpy as np
import pandas as pd
from scipy import stats as sps

OUT = os.path.join(os.path.dirname(__file__), "..", "out")
DEST = os.path.join(OUT, "appendix")
STIM = ["BOR", "CLC", "INT"]
PERMS = 20000
SEED = 90210

sur = pd.read_csv(os.path.join(OUT, "survey-episodes.csv"))
wide = pd.read_csv(os.path.join(OUT, "features-pooled-wide.csv"))
crit = pd.read_csv(os.path.join(OUT, "criterion-validity.csv"))
key = pd.read_csv(os.path.join(OUT, "keystone-decomposition.csv"))
SUBJ = sorted(sur.subject.unique())

os.makedirs(DEST, exist_ok=True)


def surf(frame, col, subjects=None):
    p = frame.pivot_table(index="subject", columns="stimulus", values=col, aggfunc="first")
    return p.reindex(index=subjects or SUBJ, columns=STIM)


def wz(t):
    m = t.mean(axis=1)
    s = t.std(axis=1, ddof=1)
    return t.sub(m, axis=0).div(s.replace(0, np.nan), axis=0)


def perm_corr(at, bt, seed):
    """rho, perm p, pearson r for two subject x stimulus tables (already z-scored)."""
    A, B = at.values, bt.values
    m = ~(np.isnan(A) | np.isnan(B))
    n = int(m.sum())
    rho = sps.spearmanr(A[m], B[m])[0]
    r = sps.pearsonr(A[m], B[m])[0]
    rng = np.random.default_rng(seed)
    null = np.empty(PERMS)
    for k in range(PERMS):
        P = np.array([rng.permutation(row) for row in B])
        mm = ~(np.isnan(A) | np.isnan(P))
        null[k] = sps.spearmanr(A[mm], P[mm])[0]
    return n, rho, float((np.abs(null) >= abs(rho)).mean()), r


def sign_test(pos, neg):
    n = pos + neg
    if n == 0:
        return float("nan")
    k = max(pos, neg)
    return min(1.0, float(sum(sps.binom.pmf(range(k, n + 1), n, 0.5)) * 2))


def paired(item_col, feat=None, subjects=None):
    """Own most-boring vs own most-engaging margins for a survey item or feature column."""
    subjects = subjects or SUBJ
    diffs = {}
    for sid in subjects:
        g = sur[sur.subject == sid]
        gb = g.sort_values(["boredom", "engagement"], ascending=[False, True]).iloc[0]
        ge = g.sort_values(["engagement", "boredom"], ascending=[False, True]).iloc[0]
        src = wide if feat else sur
        col = feat or item_col
        a = src[(src.subject == sid) & (src.stimulus == gb.stimulus)][col]
        b = src[(src.subject == sid) & (src.stimulus == ge.stimulus)][col]
        if len(a) and len(b) and pd.notna(a.iloc[0]) and pd.notna(b.iloc[0]):
            diffs[sid] = float(a.iloc[0] - b.iloc[0])
    pos = sum(1 for v in diffs.values() if v > 0)
    neg = sum(1 for v in diffs.values() if v < 0)
    tie = sum(1 for v in diffs.values() if v == 0)
    return pos, neg, tie, sign_test(pos, neg)


def fmt(x, nd=3):
    return "--" if x is None or (isinstance(x, float) and np.isnan(x)) else f"{x:+.{nd}f}"


def fp(p):
    if p is None or (isinstance(p, float) and np.isnan(p)):
        return "--"
    return "$<$0.0001" if p < 0.0001 else f"{p:.4f}"


def write(name, caption_comment, header, rows, align):
    lines = [f"% {name} — {caption_comment}",
             f"% generated by analysis/appendix_tables.py, seeds fixed, tree convention",
             f"\\begin{{tabular}}{{{align}}}", "\\hline",
             header + " \\\\", "\\hline"]
    lines += [r + " \\\\" for r in rows]
    lines += ["\\hline", "\\end{tabular}"]
    path = os.path.join(DEST, name + ".tex")
    open(path, "w").write("\n".join(lines) + "\n")
    print(f"wrote {name}.tex ({len(rows)} data rows)")


# ---------------------------------------------------------------- D1 criterion table
d = crit[crit.round_scope == "pooled"] if "round_scope" in crit.columns else crit
rows = []
for ch in d.channel.unique():
    b = d[(d.channel == ch) & (d.criterion == "boredom")].iloc[0]
    e = d[(d.channel == ch) & (d.criterion == "engagement")].iloc[0]
    rows.append(f"{ch} & {int(b.n)} & {fmt(b.rho)} & {fp(b.p_perm)} & {fmt(b.pearson_r)}"
                f" & {fmt(e.rho)} & {fp(e.p_perm)} & {fmt(e.pearson_r)}")
write("D1-criterion-full",
      "every channel against both ratings; Spearman with within-participant permutation p, "
      "Pearson beside it; pooled 36 episodes",
      "channel & $n$ & $\\rho_{bor}$ & $p$ & $r_{bor}$ & $\\rho_{eng}$ & $p$ & $r_{eng}$",
      rows, "lccccccc")

# ---------------------------------------------------------------- D2 per-round split
rows = []
for ch in ["gaze deviation (per-participant baseline)", "eye closure"]:
    for critname in ["boredom", "engagement"]:
        cells = []
        for scope in ["R1", "R2", "pooled"]:
            r0 = crit[(crit.channel == ch) & (crit.criterion == critname)
                      & (crit.round_scope == scope)]
            r0 = r0.iloc[0]
            cells.append(f"{fmt(r0.rho)} ({fp(r0.p_perm)})")
        rows.append(f"{ch} & {critname} & " + " & ".join(cells))
write("D2-per-round",
      "the two load-bearing channels split by round; Round 2 significance is per the "
      "12-episode within-participant permutation; no raw magnitudes cross rounds",
      "channel & rating & Round 1 ($n$=24) & Round 2 ($n$=12) & pooled ($n$=36)",
      rows, "llccc")

# ---------------------------------------------------------------- D3 whole-survey battery
targets = [("boredom", surf(sur, "boredom")), ("engagement", surf(sur, "engagement")),
           ("gaze", surf(wide, "gaze_deg_median_subject")),
           ("closure", surf(wide, "closure_frac"))]
items = ["sleep_fight", "fatigue_after", "minutes_until_bored", "depletion",
         "fatigue_prior", "felt_duration_ratio"]
rows = []
seed = SEED
for item in items:
    it = wz(surf(sur, item))
    cells = []
    for tname, tt in targets:
        n, rho, pp, _ = perm_corr(wz(tt), it, seed)
        seed += 1
        cells.append(f"{fmt(rho)} ({fp(pp)})")
    pos, neg, tie, sp = paired(item)
    rows.append(f"{item.replace('_', ' ')} & " + " & ".join(cells)
                + f" & {pos}/{neg}/{tie} & {fp(sp)}")
write("D3-survey-battery",
      "every survey item against both ratings and both eye measures (rho, permutation p), "
      "with the within-participant paired tally (agree/contra/tied) and exact sign p",
      "item & vs boredom & vs engagement & vs gaze & vs closure & paired & sign $p$",
      rows, "lcccccc")

# ---------------------------------------------------------------- D4 decomposition + sweep
counts = key.category.value_counts()
cz = -wz(surf(wide, "closure_frac"))
gz = -wz(surf(wide, "gaze_deg_median_subject"))
sb = key.set_index(["subject", "stimulus"]).selfreport_bored
sweep = {}
for nm, z in [("eye closure alone", cz), ("gaze deviation alone", gz),
              ("both (the composite)", (cz + gz) / 2)]:
    nd = sum(1 for s in z.index for st in STIM
             if z.loc[s, st] > 0 and bool(sb.loc[(s, st)]))
    sweep[nm] = nd
rows = [f"concordant-bored & {counts.get('concordant-bored', 0)}",
        f"concordant-engaged & {counts.get('concordant-engaged', 0)}",
        f"divergent & {counts.get('divergent', 0)}",
        f"reverse & {counts.get('reverse', 0)}"]
rows += [f"divergent under {k} & {v}" for k, v in sweep.items()]
write("D4-decomposition-sweep",
      "the four-category decomposition across all 36 episodes, and the divergent count "
      "under each single-measure definition (weighting robustness)",
      "category / definition & episodes", rows, "lc")

# ---------------------------------------------------------------- D5 per-participant matrix
rows = []
for sid in SUBJ:
    for st in STIM:
        w0 = wide[(wide.subject == sid) & (wide.stimulus == st)].iloc[0]
        s0 = sur[(sur.subject == sid) & (sur.stimulus == st)].iloc[0]
        k0 = key[(key.subject == sid) & (key.stimulus == st)].iloc[0]
        mb = "--" if pd.isna(s0.minutes_until_bored) else f"{s0.minutes_until_bored:g}"
        rows.append(
            f"{sid} & {st} & {100*w0.closure_frac:.1f} & {w0.gaze_deg_median_subject:.1f}"
            f" & {int(s0.boredom)} & {int(s0.engagement)} & {int(s0.sleep_fight)} & {mb}"
            f" & {s0.felt_duration_ratio:.2f} & {int(s0.fatigue_prior)}"
            f" & {int(s0.fatigue_after)} & {k0.category}")
write("D5-per-participant",
      "all 36 episodes: eye measures (closure %, gaze deviation deg), all seven items "
      "(felt duration as the ratio), and the decomposition category; film code is an "
      "episode identifier only",
      "subj & ep & clo\\% & gaze & bor & eng & slp & min & felt & fat$_0$ & fat$_1$ & category",
      rows, "llcccccccccl")

# ---------------------------------------------------------------- D6 with/without S06
pairs = [("gaze deviation", "gaze_deg_median_subject", True),
         ("eye closure", "closure_frac", True),
         ("sleep-fight", "sleep_fight", False),
         ("fatigue after", "fatigue_after", False)]
rows = []
seed = SEED + 500
S11 = [s for s in SUBJ if s != "S06"]
for label, col, is_feat in pairs:
    src = wide if is_feat else sur
    for critname in ["boredom", "engagement"]:
        cells = []
        for subjects in (SUBJ, S11):
            ct = wz(surf(sur, critname, subjects))
            at = wz(surf(src, col, subjects))
            n, rho, pp, _ = perm_corr(at, ct, seed)
            seed += 1
            cells.append(f"{fmt(rho)} ({fp(pp)})")
        rows.append(f"{label} & {critname} & " + " & ".join(cells))
tal = []
for label, col, is_feat in pairs:
    a12 = paired(col, feat=col if is_feat else None)
    a11 = (lambda p: p)(None)
    p12 = paired(col, feat=col if is_feat else None, subjects=SUBJ)
    p11 = paired(col, feat=col if is_feat else None, subjects=S11)
    tal.append(f"{label} & paired tally & {p12[0]}/{p12[1]}/{p12[2]} ({fp(p12[3])})"
               f" & {p11[0]}/{p11[1]}/{p11[2]} ({fp(p11[3])})")
write("D6-s06-comparison",
      "every load-bearing association with S06 included (n=12) and excluded (n=11, "
      "re-standardized from scratch); S06 is retained in all reported results",
      "measure & rating & with S06 & without S06", rows + tal, "llcc")

# ---------------------------------------------------------------- D7 EEG retention + flat channels
try:
    ret = pd.read_csv(os.path.join(OUT, "eeg-retention-snr.csv"))
    rows = []
    for _, r0 in ret.iterrows():
        cells = " & ".join(str(r0[c]) if not isinstance(r0[c], float) else f"{r0[c]:.1f}"
                           for c in ret.columns[1:])
        rows.append(f"{r0[ret.columns[0]]} & {cells}")
    write("D7a-eeg-retention", "EEG retention/SNR by cell (the evidence behind D-16)",
          " & ".join(ret.columns), rows, "l" + "c" * (len(ret.columns) - 1))
except Exception as e:
    print("D7a skipped:", e)
flat = crit[(crit.round_scope == "pooled")
            & crit.channel.isin(["pupil dilation", "cognitive load", "HR"])]
rows = []
for ch in ["pupil dilation", "cognitive load", "HR"]:
    b = flat[(flat.channel == ch) & (flat.criterion == "boredom")].iloc[0]
    e = flat[(flat.channel == ch) & (flat.criterion == "engagement")].iloc[0]
    rows.append(f"{ch} & {fmt(b.rho)} ({fp(b.p_perm)}) & {fmt(e.rho)} ({fp(e.p_perm)})")
write("D7b-flat-channels",
      "the excluded channels' criterion rows — the numbers that make the exclusions "
      "non-arbitrary",
      "channel & vs boredom & vs engagement", rows, "lcc")

# ---------------------------------------------------------------- D8 closure episode counts
rows = []
for rn, fn in [("Round 1", "r1-closure-episodes.csv"), ("Round 2", "r2-closure-episodes.csv")]:
    ep = pd.read_csv(os.path.join(OUT, fn))
    if "variant" in ep.columns:
        ep = ep[ep.variant == "unified"]
    blink = int((ep.kind == "blink").sum())
    ext = int((ep.kind == "extended").sum())
    longest = float(ep.duration_s.max())
    rows.append(f"{rn} & {blink + ext} & {blink} & {ext} & {longest:.1f}")
write("D8-closure-episodes",
      "closure events per round: total, blink-length (≤500 ms), extended, longest single "
      "event (s)",
      "round & events & blink-length & extended & longest (s)", rows, "lcccc")

print("\nSPOT CHECKS")
g = crit[(crit.channel == "gaze deviation (per-participant baseline)")
         & (crit.criterion == "boredom") & (crit.round_scope == "pooled")].iloc[0]
print(f"  D1 gaze/boredom from CSV: rho {g.rho:+.3f} (expect +0.590)")
print(f"  D4 decomposition: {dict(counts)} (expect 13/11/9/3); sweep {sweep}")
