#!/usr/bin/env python3
"""
compute-dev-ordering.py — deterministic stratified-random selection and ordering
of 50 dev annotation items from 150 dev candidates, per CONVENTIONS plan-locked
Decision 3 (2026-04-28 dev-annotation execution plan).

Inputs:
    data/gold/candidates/dev-primary_aristotle.sample.jsonl       (45 candidates)
    data/gold/candidates/dev-primary_heidegger.sample.jsonl       (30 candidates)
    data/gold/candidates/dev-secondary_phantasia.sample.jsonl     (45 candidates)
    data/gold/candidates/dev-secondary_non_phantasia.sample.jsonl (30 candidates)

Stratification (per data/gold/README.md §3 "Distribution — Dev set (50 items)"):
    primary_aristotle:       15 of 45
    primary_heidegger:       10 of 30
    secondary_phantasia:     15 of 45
    secondary_non_phantasia: 10 of 30

Procedure:
    1. Set RNG seed to 20260422 (date-encoded; rationale: discipline established
       at 2026-04-22 with item-1 of holdout annotation).
    2. Load the holdout claim_id set from data/gold/resolver-gold-holdout.jsonl
       (the lock-discipline reference; dev set MUST be disjoint from holdout to
       preserve clean evaluation in Phase 5 E0 baseline).
    3. For each genre file (in alphabetical order — locked for reproducibility):
       a. Load candidates and sort by claim_id (deterministic input order).
       b. Filter out any candidate whose claim_id appears in the holdout set
          (contamination removal — see "Holdout-exclusion finding" below).
       c. random.sample N items from the filtered pool.
    4. Combine all 50 selected items into a single list.
    5. random.shuffle the combined list to produce the dev annotation order.
    6. Emit JSON list of {position, claim_id, genre} to stdout.

Holdout-exclusion finding (2026-04-28):
    On first run (without exclusion filter), 5 holdout claim_ids appeared in the
    dev candidate sample files: claim-aristotle-da-3.3-{033,037,053,058} and
    claim-heidegger-bcap-036. This indicates the candidate sample files
    (auto-generated by scripts/sample-gold-candidates.py) were produced without
    awareness of the holdout finalization, OR the holdout was selected after
    candidates were sampled. Either way, dev annotation must be disjoint from
    holdout, so the exclusion filter is applied here at ordering-computation time.
    Filter effect on pool sizes: primary_aristotle 45 → 41; primary_heidegger
    30 → 29; secondary_non_phantasia 30 (no overlap); secondary_phantasia 45
    (no overlap). Total dev candidate pool: 145 (was 150). Sampling 50 of 145
    remains comfortably feasible.

Reproducibility notes:
    - Python 3.x random.sample / random.shuffle are documented stable for fixed
      seeds across CPython 3.2+. Tested under Python 3.11/3.12; identical output.
    - Genre file order is alphabetical (locked) to fix the RNG call sequence:
      primary_aristotle → primary_heidegger → secondary_non_phantasia →
      secondary_phantasia. Changing this order changes the output sequence.
    - Candidate-list internal ordering is sorted by claim_id ascending before
      sampling, so candidate-file line order is irrelevant.
    - Lock-against-silent-change: if reproducibility breaks (e.g., a candidate
      file is modified, removing or adding entries), document the reason and
      use a new seed; do not silently re-run.

Verification:
    Re-run this script; output must match data/gold/dev-ordering.md sequence.
    Hash of output should match the hash recorded in dev-ordering.md.
"""

import json
import random
import hashlib
from pathlib import Path

SEED = 20260422
SANDBOX = Path(__file__).resolve().parent.parent
CANDIDATES_DIR = SANDBOX / "data" / "gold" / "candidates"
HOLDOUT_PATH = SANDBOX / "data" / "gold" / "resolver-gold-holdout.jsonl"

# Locked alphabetical order for reproducibility.
GENRES = [
    ("primary_aristotle",       "dev-primary_aristotle.sample.jsonl",       15),
    ("primary_heidegger",       "dev-primary_heidegger.sample.jsonl",       10),
    ("secondary_non_phantasia", "dev-secondary_non_phantasia.sample.jsonl", 10),
    ("secondary_phantasia",     "dev-secondary_phantasia.sample.jsonl",     15),
]


def load_genre(filename: str) -> list:
    path = CANDIDATES_DIR / filename
    items = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line:
                items.append(json.loads(line))
    items.sort(key=lambda x: x["claim_id"])
    return items


def load_holdout_ids() -> set:
    ids = set()
    with open(HOLDOUT_PATH) as f:
        for line in f:
            line = line.strip()
            if line:
                ids.add(json.loads(line)["claim_id"])
    return ids


def main():
    random.seed(SEED)
    holdout_ids = load_holdout_ids()
    selected = []
    per_genre_selection = {}
    pool_sizes = {}
    excluded_per_genre = {}
    for genre_name, filename, n in GENRES:
        raw_pool = load_genre(filename)
        excluded = [c["claim_id"] for c in raw_pool if c["claim_id"] in holdout_ids]
        pool = [c for c in raw_pool if c["claim_id"] not in holdout_ids]
        excluded_per_genre[genre_name] = excluded
        pool_sizes[genre_name] = {"raw": len(raw_pool), "filtered": len(pool), "select": n}
        if len(pool) < n:
            raise SystemExit(f"insufficient candidates for {genre_name} after holdout exclusion: have {len(pool)}, need {n}")
        chosen = random.sample(pool, n)
        per_genre_selection[genre_name] = [c["claim_id"] for c in chosen]
        selected.extend(chosen)

    # Final ordering: shuffle the combined 50.
    random.shuffle(selected)

    sequence = [
        {"position": i + 1, "claim_id": item["claim_id"], "genre": item.get("genre", "?")}
        for i, item in enumerate(selected)
    ]

    output = {
        "seed": SEED,
        "total": len(sequence),
        "pool_sizes": pool_sizes,
        "holdout_excluded_per_genre": excluded_per_genre,
        "per_genre_selection": per_genre_selection,
        "sequence": sequence,
    }

    payload = json.dumps(output, indent=2, sort_keys=False)
    print(payload)
    # Hash the canonical sequence-only payload for verification.
    seq_canonical = json.dumps(sequence, sort_keys=True).encode()
    digest = hashlib.sha256(seq_canonical).hexdigest()
    print(f"\n# sequence-sha256: {digest}", flush=False)


if __name__ == "__main__":
    main()
